package com.prabhash.payments.upi

import java.util.UUID

/**
 * Lifecycle of one UPI launch started by this library.
 *
 * [RESULT_UNKNOWN] means no client result is available yet. It is not a failed payment.
 * [RESULT_RECEIVED] means an activity result was bound to this attempt. The [UpiResponse]
 * inside it is still only a client report.
 */
enum class UpiAttemptState {
    IDLE,
    LAUNCHING,
    WAITING_FOR_RESULT,
    RESULT_RECEIVED,
    RESULT_UNKNOWN,
    LAUNCH_FAILED
}

/**
 * One payment launch. [id] is generated by this library. A UPI app does not echo it.
 * [transactionRef] is the merchant reference sent as `tr` and is the only value a UPI app
 * might return that can be matched to this attempt.
 */
data class UpiPaymentAttempt(
    val id: String,
    val transactionRef: String,
    val state: UpiAttemptState,
    val clientResponse: UpiResponse? = null,
    val launchError: UpiPaymentException? = null,
    internal val requiresReferenceMatch: Boolean = false
)

/** Result of asking to start a payment while another attempt may already be open. */
sealed class UpiAttemptStart {
    data class Started(val attempt: UpiPaymentAttempt) : UpiAttemptStart()
    data class Rejected(val active: UpiPaymentAttempt) : UpiAttemptStart()
}

/** Why [UpiResultDispatcher.onActivityResult] left the current attempt unchanged. */
enum class UpiIgnoreReason {
    NO_ACTIVE_ATTEMPT,
    ATTEMPT_NOT_WAITING,
    STALE_REFERENCE,
    UNCORRELATED
}

/** Outcome of a client callback. */
sealed class UpiResultBinding {
    data class Accepted(val attempt: UpiPaymentAttempt) : UpiResultBinding()
    data class Ignored(val reason: UpiIgnoreReason) : UpiResultBinding()
}

/**
 * Restorable attempt record. [clientResponse] is not included; it can contain payment data.
 * [clientStatus] is the parsed status only, and only after a result was bound.
 */
data class UpiAttemptSnapshot(
    val attemptId: String,
    val transactionRef: String,
    val state: UpiAttemptState,
    val requiresReferenceMatch: Boolean,
    val orphanCallbackPossible: Boolean,
    val clientStatus: UpiPaymentStatus? = null
)

/**
 * Tracks a single outstanding UPI launch and decides which callbacks belong to it.
 *
 * [tryStart] fails while an attempt is [UpiAttemptState.LAUNCHING] or
 * [UpiAttemptState.WAITING_FOR_RESULT]. A second payment does not replace the first.
 *
 * Android delivers every result for one registered launcher to the same callback, with no attempt
 * id. This class therefore keeps only one outstanding launch. A callback is applied to that launch
 * only. After an attempt ends without a bound result, a later attempt accepts a callback only when
 * the payload's transaction reference equals that later attempt. A payload with no reference is
 * left unbound, because it cannot be told apart from the earlier launch. A UPI app is not required
 * to return `txnRef`.
 *
 * Save [snapshot] in instance state and pass it to [restore] after recreation, including process
 * death. Do that before the Activity is started, so a pending activity result is applied to the
 * restored attempt. The dispatcher does not hold an Activity.
 */
class UpiResultDispatcher(
    private val nextAttemptId: () -> String = { UUID.randomUUID().toString() }
) {
    private val lock = Any()
    private var orphanCallbackPossible = false

    var attempt: UpiPaymentAttempt? = null
        private set

    val state: UpiAttemptState
        get() = attempt?.state ?: UpiAttemptState.IDLE

    /** Starts an attempt, or returns the attempt that is still launching or waiting. */
    fun tryStart(transactionRef: String): UpiAttemptStart = synchronized(lock) {
        val current = attempt
        if (current != null && current.state.isOpen) {
            return UpiAttemptStart.Rejected(current)
        }
        val started = UpiPaymentAttempt(
            id = nextAttemptId(),
            transactionRef = transactionRef,
            state = UpiAttemptState.LAUNCHING,
            requiresReferenceMatch = orphanCallbackPossible
        )
        attempt = started
        UpiAttemptStart.Started(started)
    }

    /**
     * Moves [attemptId] from launching to waiting.
     * If the activity result was delivered during [androidx.activity.result.ActivityResultLauncher.launch],
     * the attempt is already [UpiAttemptState.RESULT_RECEIVED] and this call leaves it there.
     */
    fun markWaiting(attemptId: String): UpiPaymentAttempt? = synchronized(lock) {
        val current = attempt ?: return null
        if (current.id != attemptId) return null
        if (current.state == UpiAttemptState.RESULT_RECEIVED) return current
        if (current.state != UpiAttemptState.LAUNCHING) return null
        orphanCallbackPossible = true
        attempt = current.copy(state = UpiAttemptState.WAITING_FOR_RESULT)
        attempt
    }

    /** Records that the intent never opened. Does not mean the payment itself failed. */
    fun markLaunchFailed(attemptId: String, error: UpiPaymentException): UpiPaymentAttempt? = synchronized(lock) {
        val current = attempt ?: return null
        if (current.id != attemptId || current.state != UpiAttemptState.LAUNCHING) return null
        attempt = current.copy(state = UpiAttemptState.LAUNCH_FAILED, launchError = error)
        attempt
    }

    /**
     * Records that the user came back without a client result.
     * The payment is not marked failed. A later callback can still bind to this same attempt
     * when it can be correlated. It will not bind to a newer attempt that lacks a matching reference.
     */
    fun markInconclusive(attemptId: String): UpiPaymentAttempt? = synchronized(lock) {
        val current = attempt ?: return null
        if (current.id != attemptId || current.state != UpiAttemptState.WAITING_FOR_RESULT) return null
        attempt = current.copy(state = UpiAttemptState.RESULT_UNKNOWN, clientResponse = null)
        attempt
    }

    /**
     * Binds [response] to the current attempt when that is safe.
     * Invokes [consumer] only when the result is bound. A second callback does not invoke it again.
     */
    fun dispatch(response: UpiResponse, consumer: (UpiPaymentAttempt) -> Unit): Boolean {
        val binding = onActivityResult(response)
        if (binding !is UpiResultBinding.Accepted) return false
        consumer(binding.attempt)
        return true
    }

    fun onActivityResult(response: UpiResponse): UpiResultBinding = synchronized(lock) {
        val current = attempt ?: return UpiResultBinding.Ignored(UpiIgnoreReason.NO_ACTIVE_ATTEMPT)
        if (!current.state.canBindResult) {
            return UpiResultBinding.Ignored(UpiIgnoreReason.ATTEMPT_NOT_WAITING)
        }
        val reportedRef = response.transactionRef?.takeIf { it.isNotBlank() }
        if (reportedRef != null && reportedRef != current.transactionRef) {
            return UpiResultBinding.Ignored(UpiIgnoreReason.STALE_REFERENCE)
        }
        if (current.requiresReferenceMatch && reportedRef != current.transactionRef) {
            return UpiResultBinding.Ignored(UpiIgnoreReason.UNCORRELATED)
        }
        orphanCallbackPossible = current.requiresReferenceMatch
        attempt = current.copy(
            state = UpiAttemptState.RESULT_RECEIVED,
            clientResponse = response,
            requiresReferenceMatch = false
        )
        UpiResultBinding.Accepted(attempt!!)
    }

    fun snapshot(): UpiAttemptSnapshot = synchronized(lock) {
        val current = attempt
        UpiAttemptSnapshot(
            attemptId = current?.id.orEmpty(),
            transactionRef = current?.transactionRef.orEmpty(),
            state = current?.state ?: UpiAttemptState.IDLE,
            requiresReferenceMatch = current?.requiresReferenceMatch ?: false,
            orphanCallbackPossible = orphanCallbackPossible,
            clientStatus = current?.clientResponse?.status
        )
    }

    fun restore(snapshot: UpiAttemptSnapshot) = synchronized(lock) {
        orphanCallbackPossible = snapshot.orphanCallbackPossible
        attempt = if (snapshot.state == UpiAttemptState.IDLE || snapshot.attemptId.isEmpty()) {
            null
        } else {
            UpiPaymentAttempt(
                id = snapshot.attemptId,
                transactionRef = snapshot.transactionRef,
                state = snapshot.state,
                requiresReferenceMatch = snapshot.requiresReferenceMatch,
                clientResponse = snapshot.clientStatus?.let { status -> UpiResponse(status) }
            )
        }
    }
}

private val UpiAttemptState.isOpen: Boolean
    get() = this == UpiAttemptState.LAUNCHING || this == UpiAttemptState.WAITING_FOR_RESULT

private val UpiAttemptState.canBindResult: Boolean
    get() = this == UpiAttemptState.LAUNCHING ||
        this == UpiAttemptState.WAITING_FOR_RESULT ||
        this == UpiAttemptState.RESULT_UNKNOWN
